routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');


Route::resource('user', 'UserController')->middleware('auth');
Route::resource('listing', 'ListingController')->middleware('auth');

app/Http/Controllers/API/Listing/ManageListingController.php
<?php

namespace App\Http\Controllers\API\Listing;

use Validator;
use App\Entity\Listing;
use App\Http\Controllers\Controller;
use App\Http\Resources\ListingCollection;
use App\Supports\ApiSettings;
use Illuminate\Http\Request;

class ManageListingController extends Controller
{

	use ApiSettings;

    public function index(Request $request) { 

    	$data = $this->data;

    	$rules = [
            'latitude'            => 'required',
            'longitude'           => 'required',
        ];

        $message = [];

        $validator = Validator::make($request->input(), $rules, $message);

        if ($validator->fails()) {
            return $this->failedResponse($request, $validator->errors()->first());
        }


    	$listings = Listing::distance($request->input('latitude'), $request->input('longitude'))->get();

		array_push($data, $listings);

		$appData = $this->prepareAppData($request, $data);

        return (new ListingCollection($listings))->additional(['AppData' => $appData]);
	}
}

app/Http/Controllers/ListingController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Listing;
use Illuminate\Http\Request;

class ListingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $listings = Listing::with('user')->paginate(5);

        return view('listings.index', compact('listings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('listings.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        ##VALIDATION PART##
        $rules = [
          'name'            => 'required',
          'address'         => 'required',
          'latitude'        => 'required|numeric',
          'longitude'       => 'required|numeric',
        ];

        $message = [];

        $this->validate($request, $rules, $message);
        ##VALIDATION PART##

        ##STORE IN DB
        Listing::create([
            'list_name' => $request->input('name'),
            'address'   => $request->input('address'),
            'latitude'  => $request->input('latitude'),
            'longitude' => $request->input('longitude'),
            'submitter_id' => \Auth::user()->id,
        ]);

        ###
        return redirect()->route('listing.index')->with(['success-msg' => 'Record successfully created']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if ($listing = Listing::find($id)) {

            return view('listings.show', compact('listing'));
        }

        return redirect()->route('listing.index')->with(['error-msg' => 'Record not found.']);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if ($listing = Listing::find($id)) {

            return view('listings.edit', compact('listing'));
        }

        return redirect()->route('listing.index')->with(['error-msg' => 'Record not found.']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        ##VALIDATION PART##
        $rules = [
          'name'            => 'required',
          'address'         => 'required',
          'latitude'        => 'required|numeric',
          'longitude'       => 'required|numeric',
        ];

        $message = [];

        $this->validate($request, $rules, $message);
        ##VALIDATION PART##

        if (!$listing = Listing::find($id)) {
            return redirect()->route('listing.index')->with(['error-msg' => 'Record not found.']);
        }

        ##STORE IN DB
        $listing->update([
            'list_name' => $request->input('name'),
            'address'   => $request->input('address'),
            'latitude'  => $request->input('latitude'),
            'longitude' => $request->input('longitude'),
        ]);

        ###
        return redirect()->route('listing.index')->with(['success-msg' => 'Record successfully updated']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ($listing = Listing::find($id)) {

            $listing->delete();

            return redirect()->route('listing.index')->with(['success-msg' => 'Record successfully deleted.']);

        }

        return redirect()->route('listing.index')->with(['error-msg' => 'Record not found.']);
    }
}

resources/views/listings/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>Create New Listing
                        <a href="{{ route('listing.index') }}">
                            <button class="btn btn-success pull-right" style="float: right;">Back</button>
                        </a>
                    </h3>
                </div>

                <div class="card-body">
                    
                    <form action="{{ route('listing.store') }}" method="POST">
                        @csrf

                            @if(session('errors'))
                                <div class="alert alert-danger" role="alert">
                                    <p>Errors</p>
                                    @foreach($errors->all() as $error)
                                    &bull;{{ $error }}<br>
                                    @endforeach
                                </div>
                            @endif

                            @if(session('success-msg'))
                                <div class="alert alert-success" role="alert">
                                    <p>{{ session('success-msg') }}</p>
                                </div>
                            @endif


                        <div class="form-group col-md-6">
                            <label>Name</label>
                            <input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="e.g Starbucks">
                        </div>

                        <div class="form-group col-md-6">
                            <label>Address</label>
                            <textarea class="form-control" name="address">{{ old('address') }}</textarea>
                        </div>

                        <div class="form-group col-md-6">
                            <label>Latitude</label>
                            <input type="text" name="latitude" value="{{ old('latitude') }}" class="form-control" placeholder="e.g 3.2952">
                        </div>

                        <div class="form-group col-md-6">
                            <label>Longitude</label>
                            <input type="text" name="longitude" value="{{ old('longitude') }}" class="form-control" placeholder="e.g 3.2952">
                        </div>

                        <div class="form-group col-md-6">

                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/listings/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>Edit Listing
                        <a href="{{ route('listing.index') }}">
                            <button class="btn btn-success pull-right" style="float: right;">Back</button>
                        </a>
                    </h3>
                </div>

                <div class="card-body">
                    
                    <form action="{{ route('listing.update', $listing->id) }}" method="POST">
                        @csrf
                        @method('PUT')

                            @if(session('errors'))
                                <div class="alert alert-danger" role="alert">
                                    <p>Errors</p>
                                    @foreach($errors->all() as $error)
                                    &bull;{{ $error }}<br>
                                    @endforeach
                                </div>
                            @endif

                            @if(session('success-msg'))
                                <div class="alert alert-success" role="alert">
                                    <p>{{ session('success-msg') }}</p>
                                </div>
                            @endif


                        <div class="form-group col-md-6">
                            <label>Name</label>
                            <input type="text" name="name" value="{{ $listing->list_name }}" class="form-control" placeholder="e.g Starbucks">
                        </div>

                        <div class="form-group col-md-6">
                            <label>Address</label>
                            <textarea class="form-control" name="address">{{ $listing->address }}</textarea>
                        </div>

                        <div class="form-group col-md-6">
                            <label>Latitude</label>
                            <input type="text" name="latitude" value="{{ $listing->latitude }}" class="form-control" placeholder="e.g 3.2952">
                        </div>

                        <div class="form-group col-md-6">
                            <label>Longitude</label>
                            <input type="text" name="longitude" value="{{ $listing->longitude }}" class="form-control" placeholder="e.g 3.2952">
                        </div>

                        <div class="form-group col-md-6">

                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/listings/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>Listing
                        <a href="{{ route('listing.create') }}">
                            <button class="btn btn-success pull-right" style="float: right;">Create</button>
                        </a>
                    </h3>
                </div>

                <div class="card-body">
                    
                   @if(session('success-msg'))
                    <div class="alert alert-success" role="alert">
                        <p>{{ session('success-msg') }}</p>
                    </div>
                    @endif

                    @if(session('error-msg'))
                    <div class="alert alert-success" role="alert">
                        <p>{{ session('error-msg') }}</p>
                    </div>
                    @endif

                   <table class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Latitude</th>
                                <th>Longitude</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>

                            @forelse($listings as $listing)
                            <tr>
                                
                                <td>{{ $listing->list_name }}</td>
                                <td>{{ $listing->address }}</td>
                                <td>{{ $listing->latitude }}</td>
                                <td>{{ $listing->longitude }}</td>
                                <td>
                                    <a href="{{ route('listing.show', [$listing->id]) }}">
                                        <button class="btn btn-default btn-sm">Show</button>
                                    </a>
                                    <a href="{{ route('listing.edit', [$listing->id]) }}">
                                        <button class="btn btn-info btn-sm">Edit</button>
                                    </a>

                                    <form action="{{ route('listing.destroy', $listing->id) }}" method="POST">
                                        @method('DELETE')
                                        @csrf
                                        <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="5">No Record Found</td>
                            </tr>
                            @endforelse
                           
                        </tbody>
                    </table>

                    <div style="float:left; margin-right: 5px;">
                        <div class="pagination">
                            <h5 class="page-item"> Showing {{$listings->total()}} - {{$listings->total()}} of {{$listings->total()}}</h5>
                        </div>
                    </div>
                    <div style="float:right; margin-right: 5px;">
                        {!! $listings->appends(\Request::except('page'))->render("pagination::bootstrap-4") !!} 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/listings/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>View Listing
                        <a href="{{ route('listing.index') }}">
                            <button class="btn btn-success pull-right" style="float: right;">Back</button>
                        </a>
                    </h3>
                </div>

                <div class="card-body">
                    
                    <div class="form-group col-md-6">
                        <label>Name</label>
                        <input type="text" name="name" value="{{ $listing->list_name }}" class="form-control" placeholder="e.g Starbucks" disabled="">
                    </div>

                    <div class="form-group col-md-6">
                        <label>Address</label>
                        <textarea class="form-control" name="address" disabled="">{{ $listing->address }}</textarea>
                    </div>

                    <div class="form-group col-md-6">
                        <label>Latitude</label>
                        <input type="text" name="latitude" value="{{ $listing->latitude }}" class="form-control" placeholder="e.g 3.2952" disabled="">
                    </div>

                    <div class="form-group col-md-6">
                        <label>Longitude</label>
                        <input type="text" name="longitude" value="{{ $listing->longitude }}" class="form-control" placeholder="e.g 3.2952" disabled="">
                    </div>

                    <div class="form-group col-md-6">
                        <label>Submitter</label>
                        <input type="text" name="longitude" value="{{ $listing->user->name }}" class="form-control" placeholder="e.g 3.2952" disabled="">
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection