routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');


Route::resource('user', 'UserController')->middleware('auth');
Route::resource('listing', 'ListingController')->middleware('auth');

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Entity\User;
use Dingo\Api\Contract\Http\Validator;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        // $users = User::where('type', 'u')->get();
        $users = User::where('type', 'u')->paginate(5);

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        ##VALIDATION PART##
        $rules = [
          'name'            => 'required',
          'email'           => 'required|email|unique:users,email',
        ];

        $message = [
            'name.required'       => "Name kena isi boh.",
            'email.email'         => "Email taruk molek sikit.",
        ];

        $this->validate($request, $rules, $message);
        ##VALIDATION PART##

        ##STORE IN DB
        User::create([
            'name'      => $request->input('name'),
            'email'     => $request->email,
            'type'      => 'u', // sebab user biasa // tapi kalau tak tulis type pun tak apa-> default dia da memang "U";
            'password'  => bcrypt('password'),
        ]);

        ###
        return redirect()->route('user.index')->with(['success-msg' => 'Record successfully created']);
        ###
        // return back()->with(['success-msg' => 'Record successfully created']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if ($user = User::find($id)) {

            return view('users.show', compact('user'));
        }

        return redirect()->route('users.index')->with(['error-msg' => 'Record not found.']);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if ($user = User::find($id)) {

            return view('users.edit', compact('user'));
        }

        return redirect()->route('users.index')->with(['error-msg' => 'Record not found.']);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        ##VALIDATION PART##
        $rules = [
          'name'            => 'required',
        ];

        $message = [
            'name.required'       => "Name kena isi boh.",
        ];

        $this->validate($request, $rules, $message);
        ##VALIDATION PART##

        if (!$user = User::find($id)) {
            return redirect()->route('user.index')->with(['error-msg' => 'Record not found.']);
        }


        ###
        $user->name = $request->input('name');
        $user->save();
        ###
        // $user->update([
        //     'name'  => $request->input('name'),
        // ]);


        return redirect()->route('user.index')->with(['success-msg' => 'Record successfully updated.']);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        if ($user = User::find($id)) {

            $user->delete();

            return redirect()->route('user.index')->with(['success-msg' => 'Record successfully deleted.']);

        }

        return redirect()->route('user.index')->with(['error-msg' => 'Record not found.']);

    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>Create New User
                        <a href="{{ route('user.index') }}">
                            <button class="btn btn-success pull-right" style="float: right;">Back</button>
                        </a>
                    </h3>
                </div>

                <div class="card-body">
                    
                    <form action="{{ route('user.store') }}" method="POST">
                        @csrf

                            @if(session('errors'))
                                <div class="alert alert-danger" role="alert">
                                    <p>Errors</p>
                                    @foreach($errors->all() as $error)
                                    &bull;{{ $error }}<br>
                                    @endforeach
                                </div>
                            @endif

                            @if(session('success-msg'))
                                <div class="alert alert-success" role="alert">
                                    <p>{{ session('success-msg') }}</p>
                                </div>
                            @endif


                        <div class="form-group col-md-6">
                            <label>Name</label>
                            <input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="e.g Afirul Afzareza">
                        </div>

                        <div class="form-group col-md-6">
                            <label>Email</label>
                            <input type="email" name="email" value="{{ old('email') }}" class="form-control" placeholder="e.g afirul@gmail.com">
                        </div>

                        <div class="form-group col-md-6">

                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>Edit User Details
                        <a href="{{ route('user.index') }}">
                            <button class="btn btn-success pull-right" style="float: right;">Back</button>
                        </a>
                    </h3>
                </div>

                <div class="card-body">
                    
                    <form action="{{ route('user.update', $user->id) }}" method="POST">
                        @csrf
                        @method('PUT')

                            @if(session('errors'))
                                <div class="alert alert-danger" role="alert">
                                    <p>Errors</p>
                                    @foreach($errors->all() as $error)
                                    &bull;{{ $error }}<br>
                                    @endforeach
                                </div>
                            @endif

                            @if(session('success-msg'))
                                <div class="alert alert-success" role="alert">
                                    <p>{{ session('success-msg') }}</p>
                                </div>
                            @endif


                        <div class="form-group col-md-6">
                            <label>Name</label>
                            <input type="text" name="name" value="{{ $user->name }}" class="form-control" placeholder="e.g Afirul Afzareza">
                        </div>

                        <div class="form-group col-md-6">
                            <label>Email</label>
                            <input type="email" name="email" value="{{ $user->email }}" class="form-control" placeholder="e.g afirul@gmail.com" disabled="">
                        </div>

                        <div class="form-group col-md-6">

                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>User
                        <a href="{{ route('user.create') }}">
                            <button class="btn btn-success pull-right" style="float: right;">Create</button>
                        </a>
                    </h3>
                </div>

                <div class="card-body">
                    
                   @if(session('success-msg'))
                    <div class="alert alert-success" role="alert">
                        <p>{{ session('success-msg') }}</p>
                    </div>
                    @endif

                    @if(session('error-msg'))
                    <div class="alert alert-success" role="alert">
                        <p>{{ session('error-msg') }}</p>
                    </div>
                    @endif

                   <table class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <th>{{ $user->name }}</th>
                                    <th>{{ $user->email }}</th>
                                    <th>{{ $user->created_at->toDateTimeString() }}</th>
                                    <th>
                                        <a href="{{ route('user.show', [$user->id]) }}">
                                            <button class="btn btn-default btn-sm">Show</button>
                                        </a>
                                        <a href="{{ route('user.edit', [$user->id]) }}">
                                            <button class="btn btn-info btn-sm">Edit</button>
                                        </a>

                                        <form action="{{ route('user.destroy', $user->id) }}" method="POST">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                                        </form>
                                    </th>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>

                     <div style="float:left; margin-right: 5px;">
                        <div class="pagination">
                            <h5 class="page-item"> Showing {{$users->total()}} - {{$users->total()}} of {{$users->total()}}</h5>
                        </div>
                    </div>
                    <div style="float:right; margin-right: 5px;">
                        {!! $users->appends(\Request::except('page'))->render("pagination::bootstrap-4") !!} 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>View User Details
                        <a href="{{ route('user.index') }}">
                            <button class="btn btn-success pull-right" style="float: right;">Back</button>
                        </a>
                    </h3>
                </div>

                <div class="card-body">
                    

                    <div class="form-group col-md-6">
                        <label>Name</label>
                        <input type="text" name="name" value="{{ $user->name }}" class="form-control" placeholder="e.g Afirul Afzareza" disabled="">
                    </div>

                    <div class="form-group col-md-6">
                        <label>Email</label>
                        <input type="email" name="email" value="{{ $user->email }}" class="form-control" placeholder="e.g afirul@gmail.com" disabled="">
                    </div>
   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection